apiVersion: apps/v1
kind: Deployment
metadata:
  name: qweqiqq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qweqiqq
  template:
    metadata:
      labels:
        app: qweqiqq
    spec:
      containers:
      - image: okteto.dev/qweqiqq:latest
        name: qweqiqq
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "c9beb1c2-9f66-4598-a96e-6001469d2584"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "c9beb1c2-9f66-4598-a96e-6001469d2584"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
